apiVersion: v1
kind: Service
metadata:
  name: sms-web-service
  namespace: sms
spec:
  type: NodePort
  selector:
    app: sms-web
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007