# Generated by Django 6.0 on 2025-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_age_alter_student_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('ME', 'Mechanical'), ('CE', 'Civil')], max_length=50)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
