# Generated by Django 6.0 on 2025-12-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
